import type { Metadata } from "next";
import { Caveat } from "next/font/google";
import "./globals.css";

const caveat = Caveat({ 
  weight: '600',
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Feliz Aniversário Lenita",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={caveat.className}>{children}</body>
    </html>
  );
}
